apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-env-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: product-env-app
  template:
    metadata:
      labels:
        app: product-env-app
    spec:
      containers:
        - name: product-env-app
          image: damodar777/multi-branch-flask-app:build-7
          ports:
            - containerPort: 5000
