apiVersion: v1
kind: Service
metadata:
  name: product-env-app-service
  labels:
    app: product-env-app
spec:
  type: LoadBalancer
  selector:
    app: product-env-app
  ports:
    - name: http
      port: 80
      targetPort: 5000
      protocol: TCP